// Mocks generated by Mockito 5.0.12 from annotations
// in gamez_hub/test/src/core/games/data/repositories/game_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:gamez_hub/src/core/games/data/datasources/game_local_data_source.dart'
    as _i6;
import 'package:gamez_hub/src/core/games/data/datasources/game_remote_data_source.dart'
    as _i4;
import 'package:gamez_hub/src/core/games/data/models/game_model.dart' as _i5;
import 'package:gamez_hub/src/core/network/network_info.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get hasConnection =>
      (super.noSuchMethod(Invocation.getter(#hasConnection),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [GameRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRemoteDataSource extends _i1.Mock
    implements _i4.GameRemoteDataSource {
  MockGameRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.GameModel>> fetchGameList() =>
      (super.noSuchMethod(Invocation.method(#fetchGameList, []),
              returnValue: Future<List<_i5.GameModel>>.value(<_i5.GameModel>[]))
          as _i3.Future<List<_i5.GameModel>>);
}

/// A class which mocks [GameLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameLocalDataSource extends _i1.Mock
    implements _i6.GameLocalDataSource {
  MockGameLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.GameModel>> fetchCahedGames() =>
      (super.noSuchMethod(Invocation.method(#fetchCahedGames, []),
              returnValue: Future<List<_i5.GameModel>>.value(<_i5.GameModel>[]))
          as _i3.Future<List<_i5.GameModel>>);
  @override
  _i3.Future<void> addGameListToCache(List<_i5.GameModel>? games) =>
      (super.noSuchMethod(Invocation.method(#addGameListToCache, [games]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
