// Mocks generated by Mockito 5.0.12 from annotations
// in gamez_hub/test/src/core/games/data/datasources/game_remote_data_source_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:gamez_hub/src/core/api_client/api_client.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResponse extends _i1.Fake implements _i2.Response {}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> get({dynamic endpoint, String? query = r''}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [], {#endpoint: endpoint, #query: query}),
              returnValue: Future<_i2.Response>.value(_FakeResponse()))
          as _i4.Future<_i2.Response>);
}
