// Mocks generated by Mockito 5.0.12 from annotations
// in gamez_hub/test/src/core/games/domain/usecases/fetch_games_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gamez_hub/src/core/error/failure.dart' as _i5;
import 'package:gamez_hub/src/core/games/data/models/game_enums.dart' as _i7;
import 'package:gamez_hub/src/core/games/domain/entities/game_entity.dart'
    as _i6;
import 'package:gamez_hub/src/core/games/domain/repositories/game_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i3.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GameEntity>>> fetchGameList(
          {_i7.GamesOrdering? ordering}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchGameList, [], {#ordering: ordering}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.GameEntity>>>.value(
                      _FakeEither<_i5.Failure, List<_i6.GameEntity>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GameEntity>>>);
}
